apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
type: Opaque
data:
  BOT_TOKEN: NjkyMDgwMjQ3MTpBQUVMajVzbTBuTWhIMTM2anpLdDhBYnAwamR6dUJIMjhRcw==
  CAT_API_KEY: bGl2ZV81Q1ZqSEh6ZjdqUXI2aTc1RlZDaFNLZ3dwMUJrSG83MFVYbTJ1MlRnSFhieTIyUU5sbXpaTUQwRmR4YWVvSFpv

